import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { Navbar } from './Navbar';
import { Logo } from './Logo';
import { NavbarFooter } from './NavbarFooter';
import { navbarItems, navbarFooterItems } from '@/data';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'blueturtle.dev',
  description: 'Generated by create next app',
};

const LogoSection = () => {
  return (
    <div className="flex m-4 justify-center">
      <Logo />
    </div>
  );
};

const NavbarSection = () => {
  return (
    <div className="flex w-full justify-center">
      <Navbar items={navbarItems} />
    </div>
  );
};

const NavbarFooterSection = () => {
  return (
    <div className="flex flex-col w-full items-center justify-center bg-blue-50">
      <NavbarFooter items={navbarFooterItems} />
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <div className="flex flex-row w-full">
            <LogoSection />
            <NavbarSection />
          </div>
          <div className="m-4 border-2">{children}</div>
          <NavbarFooterSection />
        </div>
      </body>
    </html>
  );
}
