import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { DesktopNavbar } from './components/DesktopNavbar';
import { Logo } from './components/Logo';
import { MobileNavbar } from './components/MobileNavbar';
import { SearchButton } from './components/SearchButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'blueturtle.dev',
  description: 'Generated by create next app',
};

const NavbarSection = () => {
  return (
    <div className="flex flex-row w-full">
      <div className="flex m-4 justify-center">
        <Logo />
      </div>
      <div className="flex w-full justify-center">
        <DesktopNavbar />
      </div>
      <div className="flex items-center">
        <SearchButton />
      </div>
    </div>
  );
};

const FooterSection = () => {
  return (
    <div className="fixed w-screen bottom-0 justify-center">
      <MobileNavbar />
    </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          <NavbarSection />
          {children}
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
